title: Shuchang Lyu's Homepage
page-top-title: Shuchang Lyu
top-section-bg-text: Perseverance and toughness lead to victory
home-subtitle: Shuchang Lyu&ensp;|&ensp;吕书畅
copyright-text: '&copy; Shuchang Lyu 2025. All Rights Reserved.'
